baseURL = "/"
languageCode = "en-us"
title = ""
theme = "docsy"

# for static build: hugo --theme=docsy --buildDrafts

relativeURLS = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
# See https://help.farbox.com/pygments.html
pygmentsStyle = 'monokailight' 
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"


# Mounts
#[module]
#  [[module.mounts]]
#    source = "content/en"
#    target = "content"
#    lang = "en"
#  [[module.mounts]]
#    source = "static"
#    target = "static"
#  [[module.mounts]]
#    source = "layouts"
#    target = "layouts"
#  [[module.mounts]]
#    source = "data"
#    target = "data"
#  [[module.mounts]]
#    source = "assets"
#    target = "assets"
#  [[module.mounts]]
#    source = "archetypes"
#    target = "archetypes"

# Markdown Engine - Allow inline html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1

[menu]

  #[[menu.main]]
  #  identifier = "Home"
  #  name = "Home"
  #  # pre = "<i class='fa fa-heart'></i>"
  #  url = "http://pipservices.org/"
  #  weight = -110


  [[menu.main]]
    identifier = "Node"
    name = "Node.js"
    # pre = "<i class='fa fa-heart'></i>"
    url = "node/"
    weight = -100

  [[menu.main]]
    identifier = ".Net"
    name = ".Net"
    # pre = "<i class='fa fa-heart'></i>"
    url = "net/"
    weight = -90

  [[menu.main]]
    identifier = "Golang"
    name = "Golang"
    # pre = "<i class='fa fa-heart'></i>"
    url = "golang/"
    weight = -80

  [[menu.main]]
    identifier = "Dart"
    name = "Dart"
    # pre = "<i class='fa fa-heart'></i>"
    url = "dart/"
    weight = -70

  [[menu.main]]
    identifier = "Python"
    name = "Python"
    # pre = "<i class='fa fa-heart'></i>"
    url = "python/"
    weight = -60
  
  [[menu.main]]
    identifier = "Java"
    name = "Java"
    # pre = "<i class='fa fa-heart'></i>"
    url = "java/"
    weight = -50

  #[[menu.main]]
  #  identifier = "Get Started"
  #  name = "Get Started"
  #  url = "/get_started"
  #  weight = -40

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Add to collapsed navbar decorate arrows
addNavArrows = false 
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false
  

[params]
  copyright = "Enterprise Innovation Consulting LLC."
  privacy_policy = "https://policies.google.com/privacy"
  customCSS  = ["css/custom.css", "css/bootstrap.offcanvas.css"]
  customSCSS = ["scss/algolia.scss"]

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488cc3"

# Algolia search
algolia_docsearch = true
offlineSearch = false
[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true
[params.algolia]
  vars = ["title", "description", "summary", "date", "lastmod", "permalink"]
  params = ["categories", "tags"]
[outputs]
  home = ["HTML", "RSS", "JSON", "Algolia"]
  page = ["HTML", "RSS"]

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.1"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Main Site"
	url = "http://www.pipservices.org"
	icon = "my-icon fa"
        desc = "Our main Site!"
[[params.links.user]]
	name = "Email"
	url = "mailto:info@entinco.com"
	icon = "fa fa-envelope"
        desc = "Discussion and help"
[[params.links.user]]
	name ="YouTube"
	url = "https://www.youtube.com/channel/UCDXBRWYD1-08BW3miK5LVdg"
	icon = "fab fa-youtube"
        desc = "Our YouTube channel!"
[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/pipservices"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "http://github.com/pip-services"
	icon = "fab fa-github"
        desc = "Development takes place here!"