name: check site urls

on:
  workflow_dispatch:
  schedule:
    - cron:  '00 05 * * *' # UTC 0 timezone

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      
      - name: Install Python requirements
        run: pip3 install -r ./python_checker/requirements.txt

      - name: Check site urls
        run: python ./python_checker/link_checker.py
        env:
          CHECK_ONLY_IN_BODY: true
